anyproto/any-sync-node

- README.md
> README.md fixed Scorecard

- .github/workflows/release.yml
> .github/workflows/release.yml fixed RELEASE_VERSION

- nodespace/rpchandler.go
- nodespace/service.go
- nodespace/space.go
- nodespace/spacedeleter/spacedeleter.go
- nodespace/spacedeleter/spacedeleter_test.go
- nodestorage/deletionstorage.go
> GO-1981: Update deletion logic and fix

- .github/workflows/push-docker-image-reusable.yml
> push-docker-image-reusable.yml - fixed RELEASE_VERSION

- .github/workflows/coverage.yml
> .github/workflows/coverage.yml added check licenses

- nodesync/hotsync/hotsync.go
> GO-2475: Add logs for hotsync

- nodespace/rpchandler.go
> GO-2716: Add more headsync logs

- nodespace/service.go
- nodespace/treesyncer/treesyncer.go
> GO-2718: Fix tree syncer 

- go.mod
- go.sum
- nodespace/rpchandler.go
> GO-2717: Make ACL working

- etc/configs/any-sync-node1.yml
- etc/configs/any-sync-node2.yml
- go.mod
- go.sum
- nodespace/rpchandler.go
- nodespace/space.go
> GO-2755: More Acl Improvements

- .github/workflows/push-docker-image-manual.yml
- .github/workflows/push-docker-image-release.yml
> .github/workflows/push-docker-image-* added dockerfile-cmd

- go.mod
- go.sum
- nodespace/space.go
> GO-2936 fix watch err

- cmd/any-sync-node.go
> fix: bootstrap add nodeclient

- .github/workflows/push-docker-image-reusable.yml
> push-docker-image-reusable ci fix

- .github/workflows/push-docker-image-reusable.yml
- .github/workflows/release.yml
> ci push-docker-image-reusable.yml fixed rpm release version

- debug/nodedebugrpc/nodedebugrpc.go
- nodespace/mock_nodespace/mock_nodespace.go
- nodespace/service.go
- nodestorage/keys.go
- nodestorage/keys_test.go
- nodestorage/spacestorage.go
- nodestorage/spacestorage_test.go
> GO-4443 debug tree stats

- cmd/any-sync-node.go
> GO-4443 increase close deadline

- nodespace/service.go
> GO-4452 do not close spaces when getting stats

- .github/workflows/coverage-reusable.yml
> fix coverage-reusable

- nodestorage/spacestorage.go
- nodestorage/stat.go
> GO-5154 Devise metrics

- nodespace/service.go
- nodespace/space.go
> GO-5175 Add lock

- nodespace/spacedeleter/spacedeleter.go
- nodespace/spacedeleter/spacedeleter_test.go
- nodestorage/indexstorage.go
> GO-5228: Persist remove prepare record

- go.mod
- go.sum
- nodestorage/storageservice.go
> GO-5262: Fix any-sync and add stats for storages

- nodestorage/storageservice.go
> GO-5282: Fix node cache

- .github/workflows/push-docker-image-reusable.yml
> .github/workflows/push-docker-image-reusable.yml added deploy-platforms

- cmd/any-sync-node.go
- oldstorage/storageservice.go
> GO-5438: Remove migration

- go.mod
- go.sum
> GO-5504: Update any-sync

- go.mod
- go.sum
- nodehead/nodehead.go
> GO-5520: Fix legacy hash key

- go.mod
- go.sum
- nodehead/nodehead.go
- nodehead/nodehead_test.go
- nodespace/migrator/migrator.go
- nodespace/spacedeleter/spacedeleter_test.go
- nodestorage/indexstorage.go
- nodestorage/storageservice.go
- nodestorage/storageservice_test.go
- nodestorage/updater.go
- nodestorage/updater_test.go
> GO-5535: Fast node start

- go.mod
- go.sum
> GO-5710: Update validation

- nodespace/peermanager/manager.go
> GO-6124 update responsible peers
